---
title: "JsonImport"

author: "Ángel Manuel Medina Cárdenas"

date: "`r Sys.Date()`"

output:

  html_document:

    toc: true

    toc_depth: 3

    toc_float: 
      
      collapsed: false
      smooth_scroll: true
    
    number_sections: true

    theme: paper

    highlight: espresso    

    df_print: paged

    code_folding: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(httr)
library(jsonlite)
library(ggplot2)
library(dplyr)
library(scales)

base <- "https://api.covidactnow.org/v2/states.json?"
apiKey <- "apiKey=7169cf965bef4df0812220e481f57638"
urlApiCovid <- paste0(base,apiKey)

jsonData <- GET(urlApiCovid)

COVID_list <- fromJSON(rawToChar(jsonData$content), flatten = TRUE)

df <- data.frame(
  Estado = COVID_list$state,
  Poblacion = COVID_list$population
)

df <- df %>% arrange(desc(Poblacion))
```

# Uso de la API Covid-19 {.tabset .tabset-fade .tabset-pills}

Este informe recolecta información de la API de Covid-19 para desplegar los datos de la población por cada estado en los Estados Unidos.

```{r echo=FALSE}
df
```


# Gráfica de población por estado 

A continuación se muestra un grafico de barras sobre la población que tiene cada estado de USA ordenado de forma descendente

```{r echo=FALSE}
ggplot(df, aes(x = reorder(Estado, -Poblacion), y = Poblacion)) +
  geom_bar(stat = "identity", fill = "green", color = "black") +
  labs(title = "Población por Estado en EE.UU.",
       x = "Estado",
       y = "Población") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  scale_y_continuous(labels = comma)
```

